name: jamesfarha
favicon: null
layout_spectrum: 0.66839
typography_spectrum: 0.24836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73081717-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#050304'
    - '#7b4e3b'
    - '#b79687'
    - '#9ccaff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4502453643362969
  rhythmicContrast: 0.75
purpose: []
