typography_spectrum: 0.24836
color:
  brandColors:
    - '#0e0d0b'
    - '#cec4ba'
    - '#7b6953'
    - '#8692ce'
    - '#830918'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.66839
analytics:
  google: UA-73081717-1
  facebook: null
  twitter: null
name: James Farha
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: James Farha
purpose: []
