name: James Farha
favicon: null
layout_spectrum: 0.66839
typography_spectrum: 0.24836
title: Writing | Essays | Ideas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73081717-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d0b'
    - '#cec4ba'
    - '#7b6953'
    - '#8692ce'
    - '#830918'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
