name: jamesfarha
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49298
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#050304'
    - '#7b4e3b'
    - '#b79687'
    - '#9ccaff'
  brandStrength: 0.5
  lightness: 0.9897954524494708
  saturation: 0.4502453643362969
  rhythmicContrast: 0.1661070347763598
purpose: []
