name: jamesfarha
favicon: null
layout_spectrum: 0.2263230944518
typography_spectrum: 0.23537452472373843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.2937042322009802
  lightness: 0.9897954524494708
  saturation: 0.4502453643362969
  rhythmicContrast: 0.1661070347763598
purpose: []
